name: Cats and dogs CI/CD

on:
  push:
    branches:
      - step**

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v3

      - name: Configurer Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Mettre à jour pip et installer les dépendances
        run: |
          pip install --upgrade pip
          ./init_packages.sh
          pip install -r ./cats_dogs_other/requirements.txt
          pip install -r ./cats_dogs_other/label/requirements.txt

      - name: Exécuter les tests unitaires
        run: python -m unittest
